*       common4.
*       --------
*
      IMPLICIT REAL*8  (A-H,O-Z)
      PARAMETER  (NMAX=10,KMAX=10,MLD=1)
      INTEGER*2      KZ,KVEC,LISTD,KSLOW,NLIST,NAME,LIST,
     &               ILIST,JLIST,JPERT
*
      COMMON/NBODY/  X(3,NMAX),X0(3,NMAX),X0DOT(3,NMAX),F(3,NMAX),
     &               FDOT(3,NMAX),BODY(NMAX),XDOT(3,NMAX),
     &               D2(3,NMAX),D3(3,NMAX),STEP(NMAX),T0(NMAX)
*
      COMMON/PAIRS/  HT,U(4,KMAX),U0(4,KMAX),UDOT(4,KMAX),FU(4,KMAX),
     &               FUDOT(4,KMAX),FUDOT2(4,KMAX),FUDOT3(4,KMAX),
     &               H(KMAX),HDOT(KMAX),HDOT2(KMAX),HDOT3(KMAX),
     &               HDOT4(KMAX),DTAU(KMAX),TDOT2(KMAX),TDOT3(KMAX),
     &               R(KMAX),R0(KMAX),GAMMA(KMAX),
     &               UKS(10,KMAX),UKSD(10,KMAX),UKSD2(10,KMAX),
     &               UKSD3(10,KMAX),UKSD4(10,KMAX),UKSP(10,KMAX)
*
      COMMON/NAMES/  N,NTOT,NPAIRS,NCRIT,NFIX,NMERGE,NSUB,NCH,
     &               IPHASE,IFIRST,ICOMP,JCOMP,JCLOSE,KSPAIR,NSTABL,
     &               NRUN,MODEL,NC,NZERO,NBIN0,IDUM1,NAME0,KZ(40),
     &               KVEC(2*KMAX),LISTD(MLD),KSLOW(KMAX),
     &               NLIST(NMAX),NAME(NMAX),LIST(NMAX,2*KMAX)
*
      COMMON/COUNTS/ NSTEPI,NSTEPU,NICONV,NBREF,NBSTAT,NPRED,NBLOCK,
     &               NKSTRY,NKSREG,NKSHYP,NKSPER,NPRECT,NKSREF,NKSMOD,
     &               NTTRY,NTRIP,NQUAD,NMERG,NSTEPT,NSTEPQ,NSTEPC,NDISS,
     &               NTIDE,NCOLL,NSYNC,NSESC,NBESC,NMESC,NTIMER,NCHAIN,
     &               NSTEPS,NPRINT,NDUMP,NPOP(10),NCOUNT(30),NBDUM(7)
*
      COMMON/PARAMS/ CPU,ETA,ETA0,DTADJ,DELTAT,TCRIT,QE,RBAR,ZMBAR,
     &               DTMIN,RMIN,RDUM,ETAU,CMSEP2,ECLOSE,GMIN,GMAX,
     &               TWOPI,ONE3,ONE6,ONE9,ONE12,TCR0,BODYM,BODY1,
     &               SMIN,RMIN2,RMIN22,FCRIT2,
     &               TADJ,TNEXT,CPU0,CPUTOT,TLIST,DTLIST,
     &               TIME,ZMASS,RSCALE,TCR,BE(3),CMR(4),CMRDOT(4),
     &               ZKIN,POT,EBIN,EBIN0,ESUB,EMERGE,ECOLL,EDISS,ESYNC,
     &               E(12),ERROR,ERRTOT,DETOT,AZ,PCRIT,
     &               RTIDE,TSCALE,TIDAL(4),ETIDE,RSPH2,
     &               RC,VC,ZMC,RDENS(3),RHOD,RHOM,RMAX,
     &               DMIN1,DMIN2,DMIN3,DMIN4,DMINC,SBCOLL,BBCOLL,CHCOLL,
     &               DELTAS,ORBITS(9),GPRINT(9),TLASTT,TLASTS,TLASTB(9),
     &               TDUMP,DUMMY(7)
*
      COMMON/LISTS/  ILIST(2*KMAX),JLIST(NMAX),JPERT(NMAX)
