welcomepath=/etc/profile.d/dragonwel.sh

echo -e "\033[32m-------------------Welcome To Dragon System---------------------\033[0m"
echo "| Now we have 4 computer Dragon[0-3] in system                 |"
echo "| We use LDAP Server to manager the accounts                   |"
echo "| OpenSSH-lpk is supported                                     |"
#echo "| If you login in the system first time, you will need to      |"
#echo "| follow the comment to do some operations.                    |"
#echo "|  - If ask yes/no, choose yes.                                |"
#echo "|  - If need password, input your account password             |"
#echo "|  - Please use lssh to login in all other servers do same     |"
#echo "|    thing as in dragon0                                       |"
#echo "| This is used to establish ssh-public key authorization       |"
#echo "| After all servers finish this operation, the notice will     |"
#echo "| disappear.                                                   |"
echo -e "\033[31m| - It's better to use lps to check all cpu/mem in all servers |\033[0m"
echo -e "\033[31m| - Please DO NOT run more code if one server reach 8 limits!  |\033[0m"
echo -e "\033[31m| - If dragon1-3 have free cores, please run your new code in  |\033[0m"
echo -e "\033[31m|   dragon1-3 instead of dragon0!                              |\033[0m"
echo -e "\033[31m| - Please notice dragon0 processes limit is 7, it's better to |\033[0m"
echo -e "\033[31m|   leave one thread free since dragon0 is SSH host/LDAP server|\033[0m"
echo -e "\033[31m| - You can read all home directories of dragon1-3 in /dragon  |\033[0m"
echo -e "\033[31m|   of dragon0                                                 |\033[0m"
echo -e "\033[31m| - the ~/bin directory is in PATH environment, so any         |\033[0m"
echo -e "\033[31m|   executable file in ~/bin can be executed in any other place|\033[0m"
echo -e "\033[32m|--------------------Hardware information----------------------|\033[0m"
echo "| CPU: 4cores(8Threads) 3.4GHz 8M cache                        |"
echo "| Mem: 8G DDR3 1300MHz                                         |"
echo "| HD:  2T in dragon0, 1T in dragon[1-3]                        |"
echo "| GPU: Quadro 600 & Intel in dragon0, Intel in dragon[1-3]     |"
echo -e "\033[32m|------------------Useful Tools--------------------------------|\033[0m"
echo -e "| \033[33mlssh [0-3]\033[0m: login in to dragon[0-3] directly                 |"
echo -e "| \033[33mlscp -h [0-3] (-d -r) [Source File] [Target File]\033[0m            |"
echo "|           : scp files between dragon servers                 |"
echo "|           : Example: lscp -h 1 -r local_data1 server_data2   |"
echo "|           : File dir begin from your home directory like scp |"
echo "|           : Don't need to write hostname with IP             |"
echo "|           : -h [0-3] : dragon server number                  |"
echo "|           : -d       : download from server                  |"
echo "|           : -r       : File is directory                     |"
echo -e "| \033[33mlps (-n [num]) (-s [sortoption]) (-o [psoption])\033[0m             |"
echo "|           : show CPU/MEM rate in all dragon servers          |"
echo "|           : -n [num]  : show num of processes instead of 10  |"
echo "|           : -s [spt]  : use spt sort option, see ps --help   |"
echo "|                       : default: -%cpu,-%mem,-uid            |"
echo "|           : -o [pst]  : use pst ps option instead of aux     |"
echo -e "| \033[33mlsync (-s [path]) (-del)\033[0m                                     |"
echo '|           : rsync target in all servers from dragon0         |'
echo '|           : default target: ~/bin                            |'
echo "|           : -del      : delete files which don't exist       |"
echo "|                         in target of dragon0                 |"
echo "|           : -s [path] : rsync path files instead of ~/bin    |"
echo -e "\033[32m----------------------------------------------------------------\033[0m"
filetime=`stat -c %Y $welcomepath|cut -d'.' -f1`
filetimedate=`stat -c %y $welcomepath|cut -d'.' -f1`
nowtime=`date +%s`
[ `expr $nowtime - $filetime` -lt 259200 ] && echo -e "\033[43m\033[30mINFORMATION UPDATE! "$filetimedate"\033[0m"
